name: ros-ci

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ros-ci:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - noetic
        include:
          - docker_image: ubuntu:focal
            ros_distribution: noetic
            ros_version: 1
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros_ws/src
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@0.2.2
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Setuptools workaround
        run: export SETUPTOOLS_USE_DISTUTILS=stdlib
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: art-o-matic_sim
          target-ros1-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
